export const books = [
  ['GEN', 'genesis', 'Gênesis', 'Gn', 'gen', 50, 'old'],
  ['EXO', 'exodo', 'Êxodo', 'Êx', 'exod', 40, 'old'],
  ['LEV', 'levitico', 'Levítico', 'Lv', 'lev', 27, 'old'],
  ['NUM', 'numeros', 'Números', 'Nm', 'num', 36, 'old'],
  ['DEU', 'deuteronomio', 'Deuteronômio', 'Dt', 'deut', 34, 'old'],
  ['JOS', 'josue', 'Josué', 'Js', 'jos', 24, 'old'],
  ['JDG', 'juizes', 'Juízes', 'Jz', 'juiz', 21, 'old'],
  ['RUT', 'rute', 'Rute', 'Rt', 'rute', 4, 'old'],
  ['1SA', '1-samuel', '1 Samuel', '1Sm', '1sa', 31, 'old'],
  ['2SA', '2-samuel', '2 Samuel', '2Sm', '2sa', 24, 'old'],
  ['1KI', '1-reis', '1 Reis', '1Rs', '1rs', 22, 'old'],
  ['2KI', '2-reis', '2 Reis', '2Rs', '2rs', 25, 'old'],
  ['1CH', '1-cronicas', '1 Crônicas', '1Cr', '1crn', 29, 'old'],
  ['2CH', '2-cronicas', '2 Crônicas', '2Cr', '2crn', 36, 'old'],
  ['EZR', 'esdras', 'Esdras', 'Ed', 'esd', 10, 'old'],
  ['NEH', 'neemias', 'Neemias', 'Ne', 'nee', 13, 'old'],
  ['EST', 'ester', 'Ester', 'Et', 'est', 10, 'old'],
  ['JOB', 'jo', 'Jó', 'Jó', 'jo', 42, 'old'],
  ['PSA', 'salmos', 'Salmos', 'Sl', 'sal', 150, 'old'],
  ['PRO', 'proverbios', 'Provérbios', 'Pv', 'prov', 31, 'old'],
  ['ECC', 'eclesiastes', 'Eclesiastes', 'Ec', 'ecl', 12, 'old'],
  ['SNG', 'cantico-dos-canticos', 'Cântico dos Cânticos', 'Ct', 'cant', 8, 'old'],
  ['ISA', 'isaias', 'Isaías', 'Is', 'isa', 66, 'old'],
  ['JER', 'jeremias', 'Jeremias', 'Jr', 'jer', 52, 'old'],
  ['LAM', 'lamentacoes', 'Lamentações', 'Lm', 'lam', 5, 'old'],
  ['EZK', 'ezequiel', 'Ezequiel', 'Ez', 'eze', 48, 'old'],
  ['DAN', 'daniel', 'Daniel', 'Dn', 'dan', 12, 'old'],
  ['HOS', 'oseias', 'Oseias', 'Os', 'ose', 14, 'old'],
  ['JOL', 'joel', 'Joel', 'Jl', 'joel', 3, 'old'],
  ['AMO', 'amos', 'Amós', 'Am', 'amos', 9, 'old'],
  ['OBA', 'obadias', 'Obadias', 'Ob', 'oba', 1, 'old'],
  ['JON', 'jonas', 'Jonas', 'Jn', 'jon', 4, 'old'],
  ['MIC', 'miqueias', 'Miqueias', 'Mq', 'miq', 7, 'old'],
  ['NAM', 'naum', 'Naum', 'Na', 'naum', 3, 'old'],
  ['HAB', 'habacuque', 'Habacuque', 'Hc', 'hab', 3, 'old'],
  ['ZEP', 'sofonias', 'Sofonias', 'Sf', 'sof', 3, 'old'],
  ['HAG', 'ageu', 'Ageu', 'Ag', 'ageu', 2, 'old'],
  ['ZEC', 'zacarias', 'Zacarias', 'Zc', 'zac', 14, 'old'],
  ['MAL', 'malaquias', 'Malaquias', 'Ml', 'mal', 4, 'old'],
  ['MAT', 'mateus', 'Mateus', 'Mt', 'mat', 28, 'new'],
  ['MRK', 'marcos', 'Marcos', 'Mc', 'mar', 16, 'new'],
  ['LUK', 'lucas', 'Lucas', 'Lc', 'luc', 24, 'new'],
  ['JHN', 'joao', 'João', 'Jo', 'joao', 21, 'new'],
  ['ACT', 'atos', 'Atos', 'At', 'atos', 28, 'new'],
  ['ROM', 'romanos', 'Romanos', 'Rm', 'rom', 16, 'new'],
  ['1CO', '1-corintios', '1 Coríntios', '1Co', '1cor', 16, 'new'],
  ['2CO', '2-corintios', '2 Coríntios', '2Co', '2cor', 13, 'new'],
  ['GAL', 'galatas', 'Gálatas', 'Gl', 'gal', 6, 'new'],
  ['EPH', 'efesios', 'Efésios', 'Ef', 'efes', 6, 'new'],
  ['PHP', 'filipenses', 'Filipenses', 'Fp', 'fil', 4, 'new'],
  ['COL', 'colossenses', 'Colossenses', 'Cl', 'col', 4, 'new'],
  ['1TH', '1-tessalonicenses', '1 Tessalonicenses', '1Ts', '1tes', 5, 'new'],
  ['2TH', '2-tessalonicenses', '2 Tessalonicenses', '2Ts', '2tes', 3, 'new'],
  ['1TI', '1-timoteo', '1 Timóteo', '1Tm', '1tim', 6, 'new'],
  ['2TI', '2-timoteo', '2 Timóteo', '2Tm', '2tim', 4, 'new'],
  ['TIT', 'tito', 'Tito', 'Tt', 'tito', 3, 'new'],
  ['PHM', 'filemom', 'Filemom', 'Fm', 'flm', 1, 'new'],
  ['HEB', 'hebreus', 'Hebreus', 'Hb', 'heb', 13, 'new'],
  ['JAS', 'tiago', 'Tiago', 'Tg', 'tiag', 5, 'new'],
  ['1PE', '1-pedro', '1 Pedro', '1Pe', '1ped', 5, 'new'],
  ['2PE', '2-pedro', '2 Pedro', '2Pe', '2ped', 3, 'new'],
  ['1JN', '1-joao', '1 João', '1Jo', '1joao', 5, 'new'],
  ['2JN', '2-joao', '2 João', '2Jo', '2joao', 1, 'new'],
  ['3JN', '3-joao', '3 João', '3Jo', '3joao', 1, 'new'],
  ['JUD', 'judas', 'Judas', 'Jd', 'jud', 1, 'new'],
  ['REV', 'apocalipse', 'Apocalipse', 'Ap', 'apo', 22, 'new']
]
